## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Dogs2Improve - Development"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Website Dog2Improve"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  email = "lisa@dogs2improve.nl"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"

[Params.asset]
  custom_css = ["css/custom.css"]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
